"""BEACON Phase 3: Emit sources_candidate.yaml for operator TRACE merge.

Generates a TRACE-compatible sources.yaml with per-PIR source candidates,
CU-GIR/tier/region/industry/evidence_attack_groups header comments per entry,
and a top-of-file Capability-window warning per F-7 Q4.

The file is operator-merged into TRACE input/sources.yaml — NEVER overwritten.
All URL values are '<TODO: fill from candidate>' pending operator review.
"""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Any

import structlog

from beacon.analysis.element_extractor import ExtractedElements
from beacon.analysis.source_matcher import (
    geo_to_iso,
    pir_source_tiers,
    select_sources,
)
from beacon.generator.pir_builder import PIROutput

logger = structlog.get_logger(__name__)

_CONTENT_PATH = Path(__file__).parents[3] / "schema" / "content_ja.json"
_TODO_URL = "<TODO: fill from candidate>"


def _sq(val: str) -> str:
    """Return val as a YAML single-quoted scalar."""
    return "'" + val.replace("'", "''") + "'"


def _build_gir_hint(
    evidence_attack_groups: list[str],
    intelligence_requirements: list[dict[str, Any]],
) -> str:
    """Return comma-joined GIR IDs whose mitre_attack_groups intersect evidence_attack_groups."""
    if not evidence_attack_groups:
        return "n/a"
    evidence_set = set(evidence_attack_groups)
    matched: list[str] = []
    for ir in intelligence_requirements:
        if evidence_set & set(ir.get("mitre_attack_groups", [])):
            matched.append(ir["gir_id"])
    return ", ".join(matched) if matched else "n/a"


def build_sources_candidate_yaml(
    pirs: list[PIROutput],
    elements: ExtractedElements,
    schema_version: str = "0.16.0",
    generated_at: datetime | None = None,
    content_path: Path | None = None,
) -> str:
    """Build TRACE-compatible sources_candidate.yaml string.

    Per-entry comments include tier/region/industry/evidence metadata and a GIR
    hint cross-referenced from intelligence_requirements. All url fields are
    placeholders pending operator review.

    Args:
        pirs: PIRs generated by build_pirs() (P1/P2). May be empty.
        elements: Extracted business elements (provides geo/industry context).
        schema_version: BEACON schema_version string for the header comment.
        generated_at: Override timestamp for deterministic testing.
        content_path: Override path for content_ja.json (testing).

    Returns:
        YAML string for sources_candidate.yaml.
    """
    ts = (generated_at or datetime.utcnow()).strftime("%Y-%m-%dT%H:%M:%SZ")
    cpath = content_path or _CONTENT_PATH
    content = json.loads(cpath.read_text(encoding="utf-8"))
    all_sources: list[dict[str, Any]] = content.get("sources", [])
    intelligence_requirements: list[dict[str, Any]] = content.get("intelligence_requirements", [])

    org_region = geo_to_iso(elements.org_geographies)
    org_industry = elements.org_industry

    # name → {"src": dict, "pir_ids": set}
    source_map: dict[str, dict[str, Any]] = {}

    for pir in pirs:
        levels = pir_source_tiers(pir.intelligence_level)
        candidates = select_sources(
            intelligence_levels=levels,
            org_region=org_region,
            org_industry=org_industry,
            attack_groups=pir.mitre_attack_groups,
            sources=all_sources,
        )
        for src in candidates:
            name = src["name"]
            if name not in source_map:
                source_map[name] = {"src": src, "pir_ids": set()}
            source_map[name]["pir_ids"].add(pir.pir_id)

    # No PIRs: emit general candidates (no group filter, broad tier coverage)
    if not pirs:
        general = select_sources(
            intelligence_levels=["strategic", "operational", "tactical"],
            org_region=org_region,
            org_industry=org_industry,
            attack_groups=[],
            sources=all_sources,
        )
        for src in general:
            name = src["name"]
            if name not in source_map:
                source_map[name] = {"src": src, "pir_ids": set()}

    sorted_entries = sorted(source_map.items(), key=lambda x: x[0])

    lines: list[str] = []

    lines.append("# sources_candidate.yaml — BEACON-generated candidate sources for TRACE.")
    lines.append(f"# Generated: {ts}  schema_version: {schema_version}")
    lines.append("#")
    lines.append(
        "# NOTE: When ACTIVITY_WINDOW_DAYS=180 is set in the environment, Capability scores"
    )
    lines.append(
        "# will differ from BEACON 0.16.x outputs. This is expected per Initiative F window change."
    )
    lines.append("#")
    lines.append("# OPERATOR ACTION: Review each entry, fill in the url field, then merge into")
    lines.append("# TRACE input/sources.yaml. Do NOT overwrite existing sources.yaml entries.")
    lines.append("# CU-GIR IDs reference Intel 471 CU-GIR Framework (see docs/citations.md).")
    lines.append("")
    lines.append("version: 1")
    lines.append("sources:")

    for name, entry in sorted_entries:
        src = entry["src"]
        pir_ids_sorted = sorted(entry["pir_ids"])
        tier = src.get("tier", "")
        region = ", ".join(src.get("region", []))
        industry = ", ".join(src.get("industry_focus", []))
        evidence_groups = src.get("evidence_attack_groups", [])
        evidence_groups_str = ", ".join(evidence_groups) if evidence_groups else "n/a"
        evidence_derivation = src.get("evidence_derivation", "")
        feed_url_hint = src.get("feed_url_hint", "")
        gir_hint = _build_gir_hint(evidence_groups, intelligence_requirements)

        lines.append(f"  # Candidate: {name}")
        lines.append(f"  # gir_id_hint: {gir_hint}  tier: {tier}  region: {region}")
        lines.append(f"  # industry: {industry}  evidence_attack_groups: {evidence_groups_str}")
        lines.append(
            f"  # evidence_derivation: {evidence_derivation}  feed_url_hint: {feed_url_hint}"
        )
        lines.append("  - url: " + _sq(_TODO_URL))
        lines.append("    label: " + _sq(name))
        lines.append("    task: medium")
        if pir_ids_sorted:
            lines.append("    pir_ids:")
            for pid in pir_ids_sorted:
                lines.append(f"      - {pid}")
        else:
            lines.append("    pir_ids: []")
        lines.append("")

    return "\n".join(lines)


def write_sources_candidate(yaml_str: str, path: Path) -> None:
    """Write sources_candidate.yaml to path, creating parent directories."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(yaml_str, encoding="utf-8")
    logger.info("sources_candidate_written", path=str(path))
