"""Generate identity_assets.json (Initiative A) from BusinessContext.

Emits the artifact TRACE 1.1.0 validates and SAGE 0.6.0 ingests as
``Identity`` nodes plus ``HasAccess`` edges. The schema is defined in
``docs/initiative_a_identity_asset.md`` §4.1; this module is the BEACON-
side authoritative producer with ``source = beacon`` semantics.

Empty identities / has_access lists yield an artifact with empty arrays
rather than absent keys — SAGE's loader expects the keys to be present.
"""

from __future__ import annotations

from typing import Any

import structlog

from beacon.analysis.assets_generator import _normalize_asset_id
from beacon.ingest.schema import BusinessContext

logger = structlog.get_logger(__name__)


def generate_identity_assets_json(ctx: BusinessContext) -> dict[str, Any]:
    """Build the identity_assets.json payload from a BusinessContext.

    The output is structurally aligned with TRACE's
    ``IdentityAssetsDocument`` and SAGE's ``load_identity_assets`` CLI.
    No cross-reference validation is performed here — that lives in
    TRACE's ``validate_identity_assets`` (Initiative A §6.1).
    """
    identities = [
        {
            "id": ident.id,
            "name": ident.name,
            "identity_class": ident.identity_class,
            "sectors": list(ident.sectors),
            "roles": list(ident.roles),
            "description": ident.description,
        }
        for ident in ctx.identities
    ]

    # Apply the same `asset-` prefix normalization that `assets_generator`
    # does so the two artifacts share a single id form. Without this,
    # TRACE's validate_identity_assets cross-ref check fails (the assets
    # file carries `asset-CA-001` but identity_assets.json kept the raw
    # `CA-001` from the LLM extraction). 0.11.1 fix.
    has_access = [
        {
            "identity_id": ha.identity_id,
            "asset_id": _normalize_asset_id(ha.asset_id),
            "access_level": ha.access_level,
            "role": ha.role,
            "granted_at": ha.granted_at,
            "revoked_at": ha.revoked_at,
        }
        for ha in ctx.has_access
    ]

    payload = {
        "version": 1,
        "_comment": (
            f"Generated by BEACON from context: {ctx.organization.name}. "
            "Validate with TRACE before loading into SAGE: "
            "validate_identity_assets.py --identity-assets <file> --assets <file>"
        ),
        "identities": identities,
        "has_access": has_access,
    }

    logger.info(
        "identity_assets_json_generated",
        org=ctx.organization.name,
        identities=len(identities),
        has_access=len(has_access),
    )
    return payload
