"""Generate user_accounts.json (Initiative B) from BusinessContext.

Emits the artifact TRACE 1.3.0 validates and SAGE 0.7.0 ingests as
``UserAccount`` nodes plus ``AccountOnAsset`` and
``UserAccountBelongsTo`` edges. The schema is defined in
``docs/initiative_b_user_account.md`` §4.1; this module is the BEACON-
side authoritative producer with ``source = beacon`` semantics.

Empty ``user_accounts`` / ``account_on_asset`` lists yield an artifact
with empty arrays rather than absent keys — SAGE's loader expects the
keys to be present.

Asset id normalization: applies the same ``_normalize_asset_id``
helper as ``identity_assets_generator`` (`asset-` prefix). Without
this, TRACE's validate_user_accounts cross-ref against assets.json
would reject every edge as a dangling reference (Initiative A 0.11.1
incident).
"""

from __future__ import annotations

from typing import Any

import structlog

from beacon.analysis.assets_generator import _normalize_asset_id
from beacon.ingest.schema import BusinessContext

logger = structlog.get_logger(__name__)


def generate_user_accounts_json(ctx: BusinessContext) -> dict[str, Any]:
    """Build the user_accounts.json payload from a BusinessContext.

    No cross-reference validation here — that lives in TRACE's
    ``validate_user_accounts`` (Initiative B §6.1).
    """
    user_accounts = [
        {
            "id": ua.id,
            "account_login": ua.account_login,
            "display_name": ua.display_name,
            "account_type": ua.account_type,
            "is_privileged": ua.is_privileged,
            "is_service_account": ua.is_service_account,
            "identity_id": ua.identity_id,
            "description": ua.description,
        }
        for ua in ctx.user_accounts
    ]

    account_on_asset = [
        {
            "user_account_id": edge.user_account_id,
            "asset_id": _normalize_asset_id(edge.asset_id),
            "first_seen": edge.first_seen,
            "last_seen": edge.last_seen,
        }
        for edge in ctx.account_on_asset
    ]

    payload = {
        "version": 1,
        "_comment": (
            f"Generated by BEACON from context: {ctx.organization.name}. "
            "Validate with TRACE before loading into SAGE: "
            "validate_user_accounts.py --user-accounts <file> --assets <file>"
        ),
        "user_accounts": user_accounts,
        "account_on_asset": account_on_asset,
    }

    logger.info(
        "user_accounts_json_generated",
        org=ctx.organization.name,
        user_accounts=len(user_accounts),
        account_on_asset=len(account_on_asset),
    )
    return payload
